# Server Configuration
server.port=8081

# Application Configuration
spring.application.name=product-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product_db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration path
spring.liquibase.change-log=classpath:config/liquibase_changelog.yaml
spring.liquibase.clear-checksums=true